services:
  togglelabsdb:
    image: mongo:latest
    container_name: togglelabs-db
    ports:
      - "27017:27017"
    expose:
      - 27017
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: togglelabs
    #   MONGO_INITDB_ROOT_PASSWORD: togglelabs
    # volumes:
    #   - mongodb_data:/data/db
    networks:
      - togglelabs
  togglelabs_test_db:
    image: mongo:latest
    container_name: togglelabs-test-db
    ports:
      - "27017:27017"
    expose:
      - 27017
    networks:
      - togglelabs
networks:
  togglelabs:
    driver: bridge
